# Generated by Django 4.2.27 on 2026-01-15 21:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Audit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("audit_id", models.CharField(max_length=50, verbose_name="Audit ID")),
                ("title", models.CharField(max_length=300, verbose_name="Audit Title")),
                (
                    "title_ar",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="عنوان التدقيق"
                    ),
                ),
                (
                    "audit_type",
                    models.CharField(
                        choices=[
                            ("internal", "Internal Audit"),
                            ("external", "External Audit"),
                            ("regulatory", "Regulatory Audit"),
                            ("certification", "Certification Audit"),
                            ("surveillance", "Surveillance Audit"),
                        ],
                        default="internal",
                        max_length=20,
                        verbose_name="Audit Type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("in_progress", "In Progress"),
                            ("fieldwork", "Fieldwork"),
                            ("reporting", "Reporting"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="planned",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("scope", models.TextField(verbose_name="Audit Scope")),
                ("scope_ar", models.TextField(blank=True, verbose_name="نطاق التدقيق")),
                ("objectives", models.TextField(verbose_name="Audit Objectives")),
                (
                    "objectives_ar",
                    models.TextField(blank=True, verbose_name="أهداف التدقيق"),
                ),
                (
                    "external_firm",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="External Audit Firm"
                    ),
                ),
                (
                    "planned_start_date",
                    models.DateField(verbose_name="Planned Start Date"),
                ),
                ("planned_end_date", models.DateField(verbose_name="Planned End Date")),
                (
                    "actual_start_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Actual Start Date"
                    ),
                ),
                (
                    "actual_end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Actual End Date"
                    ),
                ),
                (
                    "audit_criteria",
                    models.TextField(blank=True, verbose_name="Audit Criteria"),
                ),
                (
                    "audit_criteria_ar",
                    models.TextField(blank=True, verbose_name="معايير التدقيق"),
                ),
                (
                    "methodology",
                    models.TextField(blank=True, verbose_name="Audit Methodology"),
                ),
                (
                    "methodology_ar",
                    models.TextField(blank=True, verbose_name="منهجية التدقيق"),
                ),
                (
                    "report_date",
                    models.DateField(blank=True, null=True, verbose_name="Report Date"),
                ),
                (
                    "executive_summary",
                    models.TextField(blank=True, verbose_name="Executive Summary"),
                ),
                (
                    "executive_summary_ar",
                    models.TextField(blank=True, verbose_name="الملخص التنفيذي"),
                ),
                ("conclusion", models.TextField(blank=True, verbose_name="Conclusion")),
                ("conclusion_ar", models.TextField(blank=True, verbose_name="الخلاصة")),
                (
                    "report_document",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="audits/reports/",
                        verbose_name="Audit Report",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "auditors",
                    models.ManyToManyField(
                        blank=True,
                        related_name="audits",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Audit Team",
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit",
                "verbose_name_plural": "Audits",
                "ordering": ["-planned_start_date"],
            },
        ),
        migrations.CreateModel(
            name="Control",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "control_id",
                    models.CharField(max_length=50, verbose_name="Control ID"),
                ),
                (
                    "title",
                    models.CharField(max_length=500, verbose_name="Control Title"),
                ),
                (
                    "title_ar",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="عنوان الضابط"
                    ),
                ),
                ("description", models.TextField(verbose_name="Control Description")),
                (
                    "description_ar",
                    models.TextField(blank=True, verbose_name="وصف الضابط"),
                ),
                (
                    "control_type",
                    models.CharField(
                        choices=[
                            ("preventive", "Preventive"),
                            ("detective", "Detective"),
                            ("corrective", "Corrective"),
                            ("compensating", "Compensating"),
                        ],
                        default="preventive",
                        max_length=20,
                        verbose_name="Control Type",
                    ),
                ),
                (
                    "implementation_guidance",
                    models.TextField(
                        blank=True, verbose_name="Implementation Guidance"
                    ),
                ),
                (
                    "implementation_guidance_ar",
                    models.TextField(blank=True, verbose_name="إرشادات التطبيق"),
                ),
                (
                    "testing_guidance",
                    models.TextField(blank=True, verbose_name="Testing Guidance"),
                ),
                (
                    "testing_guidance_ar",
                    models.TextField(blank=True, verbose_name="إرشادات الاختبار"),
                ),
                (
                    "evidence_requirements",
                    models.TextField(blank=True, verbose_name="Evidence Requirements"),
                ),
                (
                    "evidence_requirements_ar",
                    models.TextField(blank=True, verbose_name="متطلبات الأدلة"),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Order")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Control",
                "verbose_name_plural": "Controls",
                "ordering": ["domain", "order", "control_id"],
            },
        ),
        migrations.CreateModel(
            name="ControlFramework",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Framework Name"),
                ),
                (
                    "name_ar",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="اسم الإطار"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Framework Code"
                    ),
                ),
                ("version", models.CharField(max_length=20, verbose_name="Version")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                ("description_ar", models.TextField(blank=True, verbose_name="الوصف")),
                (
                    "issuing_body",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Issuing Body"
                    ),
                ),
                (
                    "issuing_body_ar",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="الجهة المصدرة"
                    ),
                ),
                (
                    "publication_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Publication Date"
                    ),
                ),
                (
                    "is_mandatory",
                    models.BooleanField(default=False, verbose_name="Mandatory"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Control Framework",
                "verbose_name_plural": "Control Frameworks",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ControlImplementation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_implemented", "Not Implemented"),
                            ("planned", "Planned"),
                            ("in_progress", "In Progress"),
                            ("partially_implemented", "Partially Implemented"),
                            ("implemented", "Implemented"),
                            ("not_applicable", "Not Applicable"),
                        ],
                        default="not_implemented",
                        max_length=30,
                        verbose_name="Status",
                    ),
                ),
                (
                    "maturity_level",
                    models.PositiveIntegerField(
                        choices=[
                            (0, "0 - Non-existent"),
                            (1, "1 - Initial"),
                            (2, "2 - Managed"),
                            (3, "3 - Defined"),
                            (4, "4 - Quantitatively Managed"),
                            (5, "5 - Optimizing"),
                        ],
                        default=0,
                        verbose_name="Maturity Level",
                    ),
                ),
                (
                    "implementation_details",
                    models.TextField(blank=True, verbose_name="Implementation Details"),
                ),
                (
                    "implementation_details_ar",
                    models.TextField(blank=True, verbose_name="تفاصيل التطبيق"),
                ),
                (
                    "last_tested_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Last Tested Date"
                    ),
                ),
                (
                    "next_test_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Next Test Date"
                    ),
                ),
                (
                    "test_frequency_months",
                    models.PositiveIntegerField(
                        default=12, verbose_name="Test Frequency (Months)"
                    ),
                ),
                (
                    "effectiveness_rating",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Effectiveness Rating (1-5)"
                    ),
                ),
                (
                    "gap_description",
                    models.TextField(blank=True, verbose_name="Gap Description"),
                ),
                (
                    "gap_description_ar",
                    models.TextField(blank=True, verbose_name="وصف الفجوة"),
                ),
                (
                    "remediation_plan",
                    models.TextField(blank=True, verbose_name="Remediation Plan"),
                ),
                (
                    "remediation_plan_ar",
                    models.TextField(blank=True, verbose_name="خطة المعالجة"),
                ),
                (
                    "target_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Target Implementation Date"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "control",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="implementations",
                        to="compliance.control",
                        verbose_name="Control",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="control_implementations",
                        to="core.department",
                        verbose_name="Responsible Department",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="control_implementations",
                        to="core.organization",
                        verbose_name="Organization",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_control_implementations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Control Owner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Control Implementation",
                "verbose_name_plural": "Control Implementations",
                "unique_together": {("organization", "control")},
            },
        ),
        migrations.CreateModel(
            name="ControlDomain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50, verbose_name="Domain Code")),
                ("name", models.CharField(max_length=300, verbose_name="Domain Name")),
                (
                    "name_ar",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="اسم المجال"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                ("description_ar", models.TextField(blank=True, verbose_name="الوصف")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Order")),
                (
                    "framework",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domains",
                        to="compliance.controlframework",
                        verbose_name="Framework",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subdomains",
                        to="compliance.controldomain",
                        verbose_name="Parent Domain",
                    ),
                ),
            ],
            options={
                "verbose_name": "Control Domain",
                "verbose_name_plural": "Control Domains",
                "ordering": ["framework", "order", "code"],
                "unique_together": {("framework", "code")},
            },
        ),
        migrations.AddField(
            model_name="control",
            name="domain",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="controls",
                to="compliance.controldomain",
                verbose_name="Domain",
            ),
        ),
        migrations.AddField(
            model_name="control",
            name="mapped_controls",
            field=models.ManyToManyField(
                blank=True, to="compliance.control", verbose_name="Mapped Controls"
            ),
        ),
        migrations.CreateModel(
            name="AuditFinding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "finding_id",
                    models.CharField(max_length=50, verbose_name="Finding ID"),
                ),
                (
                    "title",
                    models.CharField(max_length=300, verbose_name="Finding Title"),
                ),
                (
                    "title_ar",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="عنوان النتيجة"
                    ),
                ),
                (
                    "finding_type",
                    models.CharField(
                        choices=[
                            ("major_nc", "Major Non-Conformity"),
                            ("minor_nc", "Minor Non-Conformity"),
                            ("observation", "Observation"),
                            ("opportunity", "Opportunity for Improvement"),
                            ("positive", "Positive Finding"),
                        ],
                        default="observation",
                        max_length=20,
                        verbose_name="Finding Type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("in_progress", "In Progress"),
                            ("pending_verification", "Pending Verification"),
                            ("closed", "Closed"),
                            ("overdue", "Overdue"),
                        ],
                        default="open",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("description", models.TextField(verbose_name="Finding Description")),
                (
                    "description_ar",
                    models.TextField(blank=True, verbose_name="وصف النتيجة"),
                ),
                (
                    "criteria_reference",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Criteria Reference"
                    ),
                ),
                (
                    "evidence_collected",
                    models.TextField(blank=True, verbose_name="Evidence Collected"),
                ),
                (
                    "evidence_collected_ar",
                    models.TextField(blank=True, verbose_name="الأدلة المجمعة"),
                ),
                (
                    "risk_rating",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Risk Rating"
                    ),
                ),
                ("recommendation", models.TextField(verbose_name="Recommendation")),
                (
                    "recommendation_ar",
                    models.TextField(blank=True, verbose_name="التوصية"),
                ),
                (
                    "due_date",
                    models.DateField(blank=True, null=True, verbose_name="Due Date"),
                ),
                (
                    "management_response",
                    models.TextField(blank=True, verbose_name="Management Response"),
                ),
                (
                    "management_response_ar",
                    models.TextField(blank=True, verbose_name="استجابة الإدارة"),
                ),
                (
                    "response_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Response Date"
                    ),
                ),
                (
                    "closure_evidence",
                    models.TextField(blank=True, verbose_name="Closure Evidence"),
                ),
                (
                    "closed_date",
                    models.DateField(blank=True, null=True, verbose_name="Closed Date"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_findings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Assigned To",
                    ),
                ),
                (
                    "audit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="findings",
                        to="compliance.audit",
                        verbose_name="Audit",
                    ),
                ),
                (
                    "closed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="closed_findings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Closed By",
                    ),
                ),
                (
                    "control",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="findings",
                        to="compliance.control",
                        verbose_name="Related Control",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_findings",
                        to="core.department",
                        verbose_name="Responsible Department",
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Finding",
                "verbose_name_plural": "Audit Findings",
                "ordering": ["-finding_type", "-created_at"],
                "unique_together": {("audit", "finding_id")},
            },
        ),
        migrations.AddField(
            model_name="audit",
            name="controls",
            field=models.ManyToManyField(
                blank=True,
                related_name="audits",
                to="compliance.control",
                verbose_name="Controls Audited",
            ),
        ),
        migrations.AddField(
            model_name="audit",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_audits",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AddField(
            model_name="audit",
            name="departments",
            field=models.ManyToManyField(
                blank=True,
                related_name="audits",
                to="core.department",
                verbose_name="Departments Audited",
            ),
        ),
        migrations.AddField(
            model_name="audit",
            name="frameworks",
            field=models.ManyToManyField(
                blank=True,
                related_name="audits",
                to="compliance.controlframework",
                verbose_name="Frameworks Audited",
            ),
        ),
        migrations.AddField(
            model_name="audit",
            name="lead_auditor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="led_audits",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Lead Auditor",
            ),
        ),
        migrations.AddField(
            model_name="audit",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="audits",
                to="core.organization",
                verbose_name="Organization",
            ),
        ),
        migrations.CreateModel(
            name="GapAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assessment_id",
                    models.CharField(max_length=50, verbose_name="Assessment ID"),
                ),
                (
                    "title",
                    models.CharField(max_length=300, verbose_name="Assessment Title"),
                ),
                (
                    "title_ar",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="عنوان التقييم"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("approved", "Approved"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("assessment_date", models.DateField(verbose_name="Assessment Date")),
                ("scope", models.TextField(verbose_name="Assessment Scope")),
                ("scope_ar", models.TextField(blank=True, verbose_name="نطاق التقييم")),
                (
                    "total_controls",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Total Controls"
                    ),
                ),
                (
                    "implemented_controls",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Implemented Controls"
                    ),
                ),
                (
                    "partially_implemented",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Partially Implemented"
                    ),
                ),
                (
                    "not_implemented",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Not Implemented"
                    ),
                ),
                (
                    "not_applicable",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Not Applicable"
                    ),
                ),
                (
                    "compliance_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Compliance Score (%)",
                    ),
                ),
                (
                    "maturity_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=3,
                        null=True,
                        verbose_name="Maturity Score",
                    ),
                ),
                (
                    "executive_summary",
                    models.TextField(blank=True, verbose_name="Executive Summary"),
                ),
                (
                    "executive_summary_ar",
                    models.TextField(blank=True, verbose_name="الملخص التنفيذي"),
                ),
                (
                    "key_gaps",
                    models.TextField(blank=True, verbose_name="Key Gaps Identified"),
                ),
                (
                    "key_gaps_ar",
                    models.TextField(blank=True, verbose_name="الفجوات الرئيسية"),
                ),
                (
                    "recommendations",
                    models.TextField(blank=True, verbose_name="Recommendations"),
                ),
                (
                    "recommendations_ar",
                    models.TextField(blank=True, verbose_name="التوصيات"),
                ),
                (
                    "remediation_plan",
                    models.TextField(blank=True, verbose_name="Remediation Plan"),
                ),
                (
                    "remediation_plan_ar",
                    models.TextField(blank=True, verbose_name="خطة المعالجة"),
                ),
                (
                    "report_document",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="gap_assessments/",
                        verbose_name="Assessment Report",
                    ),
                ),
                (
                    "approved_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Approved Date"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_gap_assessments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Approved By",
                    ),
                ),
                (
                    "assessor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conducted_gap_assessments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Assessor",
                    ),
                ),
                (
                    "framework",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gap_assessments",
                        to="compliance.controlframework",
                        verbose_name="Framework",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gap_assessments",
                        to="core.organization",
                        verbose_name="Organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gap Assessment",
                "verbose_name_plural": "Gap Assessments",
                "ordering": ["-assessment_date"],
                "unique_together": {("organization", "assessment_id")},
            },
        ),
        migrations.CreateModel(
            name="Evidence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "evidence_id",
                    models.CharField(max_length=50, verbose_name="Evidence ID"),
                ),
                (
                    "title",
                    models.CharField(max_length=300, verbose_name="Evidence Title"),
                ),
                (
                    "title_ar",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="عنوان الدليل"
                    ),
                ),
                (
                    "evidence_type",
                    models.CharField(
                        choices=[
                            ("document", "Document"),
                            ("screenshot", "Screenshot"),
                            ("log", "System Log"),
                            ("report", "Report"),
                            ("configuration", "Configuration"),
                            ("interview", "Interview Notes"),
                            ("observation", "Observation"),
                            ("other", "Other"),
                        ],
                        default="document",
                        max_length=20,
                        verbose_name="Evidence Type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("expired", "Expired"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                ("description_ar", models.TextField(blank=True, verbose_name="الوصف")),
                (
                    "file",
                    models.FileField(
                        upload_to="evidence/", verbose_name="Evidence File"
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="File Size (bytes)"
                    ),
                ),
                ("collection_date", models.DateField(verbose_name="Collection Date")),
                ("valid_from", models.DateField(verbose_name="Valid From")),
                ("valid_until", models.DateField(verbose_name="Valid Until")),
                (
                    "submitted_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Submitted Date"
                    ),
                ),
                (
                    "reviewed_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Reviewed Date"
                    ),
                ),
                (
                    "review_notes",
                    models.TextField(blank=True, verbose_name="Review Notes"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "control_implementation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidences",
                        to="compliance.controlimplementation",
                        verbose_name="Control Implementation",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidences",
                        to="core.organization",
                        verbose_name="Organization",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_evidences",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Reviewed By",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submitted_evidences",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Submitted By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evidence",
                "verbose_name_plural": "Evidences",
                "ordering": ["-collection_date"],
                "unique_together": {("organization", "evidence_id")},
            },
        ),
        migrations.CreateModel(
            name="CorrectiveAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("car_id", models.CharField(max_length=50, verbose_name="CAR ID")),
                (
                    "title",
                    models.CharField(max_length=300, verbose_name="Action Title"),
                ),
                (
                    "title_ar",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="عنوان الإجراء"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("in_progress", "In Progress"),
                            ("pending_verification", "Pending Verification"),
                            ("verified", "Verified"),
                            ("closed", "Closed"),
                            ("overdue", "Overdue"),
                        ],
                        default="open",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=20,
                        verbose_name="Priority",
                    ),
                ),
                ("root_cause", models.TextField(verbose_name="Root Cause")),
                (
                    "root_cause_ar",
                    models.TextField(blank=True, verbose_name="السبب الجذري"),
                ),
                (
                    "action_description",
                    models.TextField(verbose_name="Action Description"),
                ),
                (
                    "action_description_ar",
                    models.TextField(blank=True, verbose_name="وصف الإجراء"),
                ),
                (
                    "target_date",
                    models.DateField(verbose_name="Target Completion Date"),
                ),
                (
                    "completed_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Actual Completion Date"
                    ),
                ),
                (
                    "implementation_notes",
                    models.TextField(blank=True, verbose_name="Implementation Notes"),
                ),
                (
                    "implementation_notes_ar",
                    models.TextField(blank=True, verbose_name="ملاحظات التنفيذ"),
                ),
                (
                    "verification_method",
                    models.TextField(blank=True, verbose_name="Verification Method"),
                ),
                (
                    "verification_method_ar",
                    models.TextField(blank=True, verbose_name="طريقة التحقق"),
                ),
                (
                    "verified_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Verification Date"
                    ),
                ),
                (
                    "verification_notes",
                    models.TextField(blank=True, verbose_name="Verification Notes"),
                ),
                (
                    "effectiveness_check_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Effectiveness Check Date"
                    ),
                ),
                (
                    "is_effective",
                    models.BooleanField(null=True, verbose_name="Is Effective"),
                ),
                (
                    "effectiveness_notes",
                    models.TextField(blank=True, verbose_name="Effectiveness Notes"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_corrective_actions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "finding",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="corrective_actions",
                        to="compliance.auditfinding",
                        verbose_name="Related Finding",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="corrective_actions",
                        to="core.organization",
                        verbose_name="Organization",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_corrective_actions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Action Owner",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_actions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Verified By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Corrective Action",
                "verbose_name_plural": "Corrective Actions",
                "ordering": ["-priority", "target_date"],
                "unique_together": {("organization", "car_id")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="control", unique_together={("domain", "control_id")},
        ),
        migrations.AlterUniqueTogether(
            name="audit", unique_together={("organization", "audit_id")},
        ),
    ]
