# Generated by Django 4.2.27 on 2026-01-18 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compliance", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audit",
            name="objectives",
            field=models.TextField(blank=True, verbose_name="Audit Objectives"),
        ),
        migrations.AlterField(
            model_name="audit",
            name="scope",
            field=models.TextField(blank=True, verbose_name="Audit Scope"),
        ),
        migrations.AlterField(
            model_name="auditfinding",
            name="description",
            field=models.TextField(blank=True, verbose_name="Finding Description"),
        ),
        migrations.AlterField(
            model_name="auditfinding",
            name="recommendation",
            field=models.TextField(blank=True, verbose_name="Recommendation"),
        ),
        migrations.AlterField(
            model_name="control",
            name="description",
            field=models.TextField(blank=True, verbose_name="Control Description"),
        ),
        migrations.AlterField(
            model_name="correctiveaction",
            name="action_description",
            field=models.TextField(blank=True, verbose_name="Action Description"),
        ),
        migrations.AlterField(
            model_name="correctiveaction",
            name="root_cause",
            field=models.TextField(blank=True, verbose_name="Root Cause"),
        ),
        migrations.AlterField(
            model_name="gapassessment",
            name="assessment_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Assessment Date"
            ),
        ),
        migrations.AlterField(
            model_name="gapassessment",
            name="scope",
            field=models.TextField(blank=True, verbose_name="Assessment Scope"),
        ),
    ]
