# Generated by Django 4.2.27 on 2026-01-21 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0002_alter_audit_objectives_alter_audit_scope_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control',
            name='domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='controls', to='compliance.controldomain', verbose_name='Domain'),
        ),
    ]
