# Generated by Django 4.2.27 on 2026-01-15 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FrameworkTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Framework Code"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Framework Name"),
                ),
                (
                    "name_ar",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="اسم الإطار"
                    ),
                ),
                ("version", models.CharField(max_length=20, verbose_name="Version")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                ("description_ar", models.TextField(blank=True, verbose_name="الوصف")),
                (
                    "template_data",
                    models.JSONField(default=dict, verbose_name="Template Data"),
                ),
                (
                    "mapping_data",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Mapping Data"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Framework Template",
                "verbose_name_plural": "Framework Templates",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="RegulatoryRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "framework_code",
                    models.CharField(max_length=50, verbose_name="Framework Code"),
                ),
                (
                    "requirement_id",
                    models.CharField(max_length=50, verbose_name="Requirement ID"),
                ),
                ("title", models.CharField(max_length=500, verbose_name="Title")),
                (
                    "title_ar",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="العنوان"
                    ),
                ),
                ("description", models.TextField(verbose_name="Description")),
                ("description_ar", models.TextField(blank=True, verbose_name="الوصف")),
                (
                    "requirement_type",
                    models.CharField(
                        choices=[
                            ("mandatory", "Mandatory"),
                            ("recommended", "Recommended"),
                            ("optional", "Optional"),
                        ],
                        default="mandatory",
                        max_length=20,
                        verbose_name="Requirement Type",
                    ),
                ),
                (
                    "article_reference",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Article Reference"
                    ),
                ),
                (
                    "related_control_ids",
                    models.JSONField(default=list, verbose_name="Related Control IDs"),
                ),
                (
                    "penalty_description",
                    models.TextField(blank=True, verbose_name="Penalty Description"),
                ),
                (
                    "penalty_description_ar",
                    models.TextField(blank=True, verbose_name="وصف العقوبة"),
                ),
            ],
            options={
                "verbose_name": "Regulatory Requirement",
                "verbose_name_plural": "Regulatory Requirements",
                "unique_together": {("framework_code", "requirement_id")},
            },
        ),
        migrations.CreateModel(
            name="ControlMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_framework",
                    models.CharField(max_length=50, verbose_name="Source Framework"),
                ),
                (
                    "source_control_id",
                    models.CharField(max_length=50, verbose_name="Source Control ID"),
                ),
                (
                    "target_framework",
                    models.CharField(max_length=50, verbose_name="Target Framework"),
                ),
                (
                    "target_control_id",
                    models.CharField(max_length=50, verbose_name="Target Control ID"),
                ),
                (
                    "mapping_type",
                    models.CharField(
                        choices=[
                            ("full", "Full Mapping"),
                            ("partial", "Partial Mapping"),
                            ("related", "Related"),
                        ],
                        default="full",
                        max_length=20,
                        verbose_name="Mapping Type",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                ("notes_ar", models.TextField(blank=True, verbose_name="ملاحظات")),
            ],
            options={
                "verbose_name": "Control Mapping",
                "verbose_name_plural": "Control Mappings",
                "unique_together": {
                    (
                        "source_framework",
                        "source_control_id",
                        "target_framework",
                        "target_control_id",
                    )
                },
            },
        ),
    ]
