# Generated by Django 4.2.27 on 2026-01-18 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("governance", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="policy",
            name="policy_statement",
            field=models.TextField(blank=True, verbose_name="Policy Statement"),
        ),
        migrations.AlterField(
            model_name="policy",
            name="purpose",
            field=models.TextField(blank=True, verbose_name="Purpose"),
        ),
        migrations.AlterField(
            model_name="policy",
            name="scope",
            field=models.TextField(blank=True, verbose_name="Scope"),
        ),
    ]
