# Generated by Django 4.2.27 on 2026-01-15 21:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dashboard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Dashboard Name"),
                ),
                (
                    "name_ar",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="اسم لوحة المعلومات"
                    ),
                ),
                (
                    "dashboard_type",
                    models.CharField(
                        choices=[
                            ("executive", "Executive Dashboard"),
                            ("operational", "Operational Dashboard"),
                            ("risk", "Risk Dashboard"),
                            ("compliance", "Compliance Dashboard"),
                            ("audit", "Audit Dashboard"),
                            ("bcm", "BCM Dashboard"),
                            ("custom", "Custom Dashboard"),
                        ],
                        default="custom",
                        max_length=20,
                        verbose_name="Dashboard Type",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                ("description_ar", models.TextField(blank=True, verbose_name="الوصف")),
                (
                    "is_default",
                    models.BooleanField(
                        default=False, verbose_name="Default Dashboard"
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(default=False, verbose_name="Public"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "allowed_roles",
                    models.ManyToManyField(
                        blank=True,
                        related_name="dashboards",
                        to="core.role",
                        verbose_name="Allowed Roles",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_dashboards",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Owner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dashboard",
                "verbose_name_plural": "Dashboards",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DashboardWidget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Widget Name")),
                (
                    "name_ar",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="اسم العنصر"
                    ),
                ),
                (
                    "widget_type",
                    models.CharField(
                        choices=[
                            ("kpi", "KPI Card"),
                            ("chart_bar", "Bar Chart"),
                            ("chart_line", "Line Chart"),
                            ("chart_pie", "Pie Chart"),
                            ("chart_doughnut", "Doughnut Chart"),
                            ("risk_matrix", "Risk Matrix"),
                            ("table", "Data Table"),
                            ("timeline", "Timeline"),
                            ("list", "List"),
                        ],
                        max_length=20,
                        verbose_name="Widget Type",
                    ),
                ),
                (
                    "data_source",
                    models.CharField(
                        choices=[
                            ("risks", "Risks"),
                            ("controls", "Controls"),
                            ("compliance", "Compliance"),
                            ("audits", "Audits"),
                            ("tasks", "Tasks"),
                            ("policies", "Policies"),
                            ("bcm", "BCM"),
                            ("custom", "Custom Query"),
                        ],
                        max_length=20,
                        verbose_name="Data Source",
                    ),
                ),
                (
                    "query_config",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Query Configuration"
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="primary", max_length=20, verbose_name="Color"
                    ),
                ),
                (
                    "icon",
                    models.CharField(blank=True, max_length=50, verbose_name="Icon"),
                ),
                (
                    "width",
                    models.PositiveIntegerField(
                        default=3, verbose_name="Width (columns)"
                    ),
                ),
                (
                    "height",
                    models.PositiveIntegerField(default=1, verbose_name="Height"),
                ),
                (
                    "refresh_interval",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Refresh Interval (seconds)"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Dashboard Widget",
                "verbose_name_plural": "Dashboard Widgets",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="KPI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="KPI Name")),
                (
                    "name_ar",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="اسم المؤشر"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="KPI Code"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                ("description_ar", models.TextField(blank=True, verbose_name="الوصف")),
                (
                    "calculation_query",
                    models.TextField(blank=True, verbose_name="Calculation Query"),
                ),
                (
                    "calculation_config",
                    models.JSONField(default=dict, verbose_name="Calculation Config"),
                ),
                (
                    "target_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Target Value",
                    ),
                ),
                (
                    "warning_threshold",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Warning Threshold",
                    ),
                ),
                (
                    "critical_threshold",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Critical Threshold",
                    ),
                ),
                (
                    "unit",
                    models.CharField(blank=True, max_length=20, verbose_name="Unit"),
                ),
                (
                    "trend_direction",
                    models.CharField(
                        choices=[
                            ("up_good", "Up is Good"),
                            ("down_good", "Down is Good"),
                            ("neutral", "Neutral"),
                        ],
                        default="up_good",
                        max_length=20,
                        verbose_name="Trend Direction",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "KPI",
                "verbose_name_plural": "KPIs",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ReportTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Template Name"),
                ),
                (
                    "name_ar",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="اسم القالب"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Template Code"
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("compliance", "Compliance Report"),
                            ("risk", "Risk Report"),
                            ("audit", "Audit Report"),
                            ("executive", "Executive Summary"),
                            ("bcm", "BCM Report"),
                            ("gap", "Gap Analysis Report"),
                            ("custom", "Custom Report"),
                        ],
                        max_length=20,
                        verbose_name="Report Type",
                    ),
                ),
                (
                    "output_format",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF"),
                            ("excel", "Excel"),
                            ("word", "Word"),
                            ("html", "HTML"),
                        ],
                        default="pdf",
                        max_length=10,
                        verbose_name="Output Format",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                ("description_ar", models.TextField(blank=True, verbose_name="الوصف")),
                (
                    "template_config",
                    models.JSONField(
                        default=dict, verbose_name="Template Configuration"
                    ),
                ),
                (
                    "template_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="report_templates/",
                        verbose_name="Template File",
                    ),
                ),
                (
                    "include_logo",
                    models.BooleanField(default=True, verbose_name="Include Logo"),
                ),
                (
                    "include_header",
                    models.BooleanField(default=True, verbose_name="Include Header"),
                ),
                (
                    "include_footer",
                    models.BooleanField(default=True, verbose_name="Include Footer"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Report Template",
                "verbose_name_plural": "Report Templates",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="GeneratedReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=300, verbose_name="Report Title"),
                ),
                (
                    "title_ar",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="عنوان التقرير"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("generating", "Generating"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "parameters",
                    models.JSONField(default=dict, verbose_name="Report Parameters"),
                ),
                (
                    "date_from",
                    models.DateField(blank=True, null=True, verbose_name="From Date"),
                ),
                (
                    "date_to",
                    models.DateField(blank=True, null=True, verbose_name="To Date"),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="generated_reports/",
                        verbose_name="Report File",
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="File Size (bytes)"
                    ),
                ),
                (
                    "generated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Generated At"
                    ),
                ),
                (
                    "generation_time_seconds",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Generation Time (seconds)"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Error Message"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_reports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Generated By",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generated_reports",
                        to="core.organization",
                        verbose_name="Organization",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_reports",
                        to="dashboard.reporttemplate",
                        verbose_name="Template",
                    ),
                ),
            ],
            options={
                "verbose_name": "Generated Report",
                "verbose_name_plural": "Generated Reports",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DashboardWidgetPosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("row", models.PositiveIntegerField(default=0, verbose_name="Row")),
                (
                    "column",
                    models.PositiveIntegerField(default=0, verbose_name="Column"),
                ),
                (
                    "width",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Width"
                    ),
                ),
                (
                    "height",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Height"
                    ),
                ),
                (
                    "dashboard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="widget_positions",
                        to="dashboard.dashboard",
                        verbose_name="Dashboard",
                    ),
                ),
                (
                    "widget",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="positions",
                        to="dashboard.dashboardwidget",
                        verbose_name="Widget",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dashboard Widget Position",
                "verbose_name_plural": "Dashboard Widget Positions",
                "unique_together": {("dashboard", "row", "column")},
            },
        ),
        migrations.AddField(
            model_name="dashboard",
            name="widgets",
            field=models.ManyToManyField(
                related_name="dashboards",
                through="dashboard.DashboardWidgetPosition",
                to="dashboard.dashboardwidget",
                verbose_name="Widgets",
            ),
        ),
        migrations.CreateModel(
            name="KPIValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Value"
                    ),
                ),
                ("period_date", models.DateField(verbose_name="Period Date")),
                (
                    "breakdown",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Breakdown"
                    ),
                ),
                (
                    "calculated_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Calculated At"
                    ),
                ),
                (
                    "kpi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="dashboard.kpi",
                        verbose_name="KPI",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kpi_values",
                        to="core.organization",
                        verbose_name="Organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "KPI Value",
                "verbose_name_plural": "KPI Values",
                "ordering": ["-period_date"],
                "unique_together": {("organization", "kpi", "period_date")},
            },
        ),
    ]
