# Generated by Django 4.2.27 on 2026-01-15 21:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("risk", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BCMTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("test_id", models.CharField(max_length=50, verbose_name="Test ID")),
                ("title", models.CharField(max_length=300, verbose_name="Test Title")),
                (
                    "title_ar",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="عنوان الاختبار"
                    ),
                ),
                (
                    "test_type",
                    models.CharField(
                        choices=[
                            ("tabletop", "Tabletop Exercise"),
                            ("walkthrough", "Walkthrough"),
                            ("simulation", "Simulation"),
                            ("parallel", "Parallel Test"),
                            ("full", "Full Interruption Test"),
                        ],
                        default="tabletop",
                        max_length=20,
                        verbose_name="Test Type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="planned",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("objectives", models.TextField(verbose_name="Test Objectives")),
                (
                    "objectives_ar",
                    models.TextField(blank=True, verbose_name="أهداف الاختبار"),
                ),
                ("scope", models.TextField(verbose_name="Test Scope")),
                (
                    "scope_ar",
                    models.TextField(blank=True, verbose_name="نطاق الاختبار"),
                ),
                ("scenario", models.TextField(verbose_name="Test Scenario")),
                (
                    "scenario_ar",
                    models.TextField(blank=True, verbose_name="سيناريو الاختبار"),
                ),
                ("scheduled_date", models.DateField(verbose_name="Scheduled Date")),
                (
                    "scheduled_duration_hours",
                    models.PositiveIntegerField(
                        default=2, verbose_name="Scheduled Duration (Hours)"
                    ),
                ),
                (
                    "actual_start",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Actual Start"
                    ),
                ),
                (
                    "actual_end",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Actual End"
                    ),
                ),
                (
                    "overall_result",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Overall Result"
                    ),
                ),
                (
                    "results_summary",
                    models.TextField(blank=True, verbose_name="Results Summary"),
                ),
                (
                    "results_summary_ar",
                    models.TextField(blank=True, verbose_name="ملخص النتائج"),
                ),
                (
                    "strengths_identified",
                    models.TextField(blank=True, verbose_name="Strengths Identified"),
                ),
                (
                    "strengths_identified_ar",
                    models.TextField(blank=True, verbose_name="نقاط القوة"),
                ),
                (
                    "weaknesses_identified",
                    models.TextField(blank=True, verbose_name="Weaknesses Identified"),
                ),
                (
                    "weaknesses_identified_ar",
                    models.TextField(blank=True, verbose_name="نقاط الضعف"),
                ),
                (
                    "lessons_learned",
                    models.TextField(blank=True, verbose_name="Lessons Learned"),
                ),
                (
                    "lessons_learned_ar",
                    models.TextField(blank=True, verbose_name="الدروس المستفادة"),
                ),
                (
                    "report_document",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="bcm/test_reports/",
                        verbose_name="Test Report",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "BCM Test",
                "verbose_name_plural": "BCM Tests",
                "ordering": ["-scheduled_date"],
            },
        ),
        migrations.CreateModel(
            name="BCPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plan_id", models.CharField(max_length=50, verbose_name="Plan ID")),
                ("title", models.CharField(max_length=300, verbose_name="Plan Title")),
                (
                    "title_ar",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="عنوان الخطة"
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        default="1.0", max_length=20, verbose_name="Version"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending_review", "Pending Review"),
                            ("pending_approval", "Pending Approval"),
                            ("approved", "Approved"),
                            ("active", "Active"),
                            ("under_revision", "Under Revision"),
                            ("retired", "Retired"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("scope", models.TextField(verbose_name="Plan Scope")),
                ("scope_ar", models.TextField(blank=True, verbose_name="نطاق الخطة")),
                ("objectives", models.TextField(verbose_name="Objectives")),
                ("objectives_ar", models.TextField(blank=True, verbose_name="الأهداف")),
                (
                    "activation_criteria",
                    models.TextField(verbose_name="Activation Criteria"),
                ),
                (
                    "activation_criteria_ar",
                    models.TextField(blank=True, verbose_name="معايير التفعيل"),
                ),
                (
                    "recovery_strategies",
                    models.TextField(verbose_name="Recovery Strategies"),
                ),
                (
                    "recovery_strategies_ar",
                    models.TextField(blank=True, verbose_name="استراتيجيات الاستعادة"),
                ),
                (
                    "roles_responsibilities",
                    models.TextField(verbose_name="Roles and Responsibilities"),
                ),
                (
                    "roles_responsibilities_ar",
                    models.TextField(blank=True, verbose_name="الأدوار والمسؤوليات"),
                ),
                (
                    "communication_plan",
                    models.TextField(verbose_name="Communication Plan"),
                ),
                (
                    "communication_plan_ar",
                    models.TextField(blank=True, verbose_name="خطة الاتصالات"),
                ),
                (
                    "resource_requirements",
                    models.TextField(blank=True, verbose_name="Resource Requirements"),
                ),
                (
                    "resource_requirements_ar",
                    models.TextField(blank=True, verbose_name="متطلبات الموارد"),
                ),
                (
                    "alternate_site",
                    models.TextField(
                        blank=True, verbose_name="Alternate Site Information"
                    ),
                ),
                (
                    "alternate_site_ar",
                    models.TextField(blank=True, verbose_name="معلومات الموقع البديل"),
                ),
                (
                    "document",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="bcm/plans/",
                        verbose_name="Plan Document",
                    ),
                ),
                (
                    "effective_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Effective Date"
                    ),
                ),
                (
                    "review_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Next Review Date"
                    ),
                ),
                (
                    "last_tested_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Last Tested Date"
                    ),
                ),
                (
                    "approved_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Approved Date"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_bc_plans",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Approved By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Business Continuity Plan",
                "verbose_name_plural": "Business Continuity Plans",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="BusinessFunction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "function_id",
                    models.CharField(max_length=50, verbose_name="Function ID"),
                ),
                (
                    "name",
                    models.CharField(max_length=300, verbose_name="Function Name"),
                ),
                (
                    "name_ar",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="اسم الوظيفة"
                    ),
                ),
                ("description", models.TextField(verbose_name="Description")),
                ("description_ar", models.TextField(blank=True, verbose_name="الوصف")),
                (
                    "criticality",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("essential", "Essential"),
                            ("necessary", "Necessary"),
                            ("desirable", "Desirable"),
                        ],
                        default="necessary",
                        max_length=20,
                        verbose_name="Criticality",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("under_review", "Under Review"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_functions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="business_functions",
                        to="core.department",
                        verbose_name="Department",
                    ),
                ),
                (
                    "dependent_functions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="dependencies",
                        to="bcm.businessfunction",
                        verbose_name="Dependent Functions",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="business_functions",
                        to="core.organization",
                        verbose_name="Organization",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_functions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Function Owner",
                    ),
                ),
                (
                    "parent_function",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sub_functions",
                        to="bcm.businessfunction",
                        verbose_name="Parent Function",
                    ),
                ),
                (
                    "related_assets",
                    models.ManyToManyField(
                        blank=True,
                        related_name="business_functions",
                        to="risk.asset",
                        verbose_name="Related Assets",
                    ),
                ),
            ],
            options={
                "verbose_name": "Business Function",
                "verbose_name_plural": "Business Functions",
                "ordering": ["criticality", "name"],
                "unique_together": {("organization", "function_id")},
            },
        ),
        migrations.CreateModel(
            name="CallTree",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Call Tree Name"),
                ),
                (
                    "name_ar",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="اسم شجرة الاتصال"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                ("description_ar", models.TextField(blank=True, verbose_name="الوصف")),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "last_tested",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Last Tested"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="call_trees",
                        to="core.organization",
                        verbose_name="Organization",
                    ),
                ),
                (
                    "root_caller",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="root_call_trees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Root Caller",
                    ),
                ),
            ],
            options={"verbose_name": "Call Tree", "verbose_name_plural": "Call Trees",},
        ),
        migrations.CreateModel(
            name="CrisisManagementTeam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Team Name")),
                (
                    "name_ar",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="اسم الفريق"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crisis_teams",
                        to="core.organization",
                        verbose_name="Organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Crisis Management Team",
                "verbose_name_plural": "Crisis Management Teams",
            },
        ),
        migrations.CreateModel(
            name="DisasterRecoveryPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plan_id", models.CharField(max_length=50, verbose_name="Plan ID")),
                ("title", models.CharField(max_length=300, verbose_name="Plan Title")),
                (
                    "title_ar",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="عنوان الخطة"
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        default="1.0", max_length=20, verbose_name="Version"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending_approval", "Pending Approval"),
                            ("approved", "Approved"),
                            ("active", "Active"),
                            ("under_revision", "Under Revision"),
                            ("retired", "Retired"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("scope", models.TextField(verbose_name="Plan Scope")),
                ("scope_ar", models.TextField(blank=True, verbose_name="نطاق الخطة")),
                ("covered_systems", models.TextField(verbose_name="Covered Systems")),
                (
                    "covered_systems_ar",
                    models.TextField(blank=True, verbose_name="الأنظمة المشمولة"),
                ),
                (
                    "recovery_procedures",
                    models.TextField(verbose_name="Recovery Procedures"),
                ),
                (
                    "recovery_procedures_ar",
                    models.TextField(blank=True, verbose_name="إجراءات الاستعادة"),
                ),
                ("backup_strategy", models.TextField(verbose_name="Backup Strategy")),
                (
                    "backup_strategy_ar",
                    models.TextField(
                        blank=True, verbose_name="استراتيجية النسخ الاحتياطي"
                    ),
                ),
                (
                    "backup_location",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Backup Location"
                    ),
                ),
                (
                    "backup_frequency",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Backup Frequency"
                    ),
                ),
                (
                    "dr_site_location",
                    models.TextField(blank=True, verbose_name="DR Site Location"),
                ),
                (
                    "dr_site_location_ar",
                    models.TextField(blank=True, verbose_name="موقع التعافي"),
                ),
                (
                    "vendor_contacts",
                    models.TextField(blank=True, verbose_name="Vendor Contacts"),
                ),
                (
                    "document",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="bcm/dr_plans/",
                        verbose_name="Plan Document",
                    ),
                ),
                (
                    "effective_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Effective Date"
                    ),
                ),
                (
                    "review_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Next Review Date"
                    ),
                ),
                (
                    "last_tested_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Last Tested Date"
                    ),
                ),
                (
                    "approved_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Approved Date"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_dr_plans",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Approved By",
                    ),
                ),
                (
                    "bc_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dr_plans",
                        to="bcm.bcplan",
                        verbose_name="Related BCP",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_dr_plans",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dr_plans",
                        to="core.organization",
                        verbose_name="Organization",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_dr_plans",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Plan Owner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Disaster Recovery Plan",
                "verbose_name_plural": "Disaster Recovery Plans",
                "ordering": ["-updated_at"],
                "unique_together": {("organization", "plan_id")},
            },
        ),
        migrations.CreateModel(
            name="CallTreeNode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=1, verbose_name="Call Order"),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="Phone")),
                (
                    "alternate_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Alternate Phone"
                    ),
                ),
                (
                    "call_tree",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nodes",
                        to="bcm.calltree",
                        verbose_name="Call Tree",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="bcm.calltreenode",
                        verbose_name="Parent Node",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="call_tree_nodes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Call Tree Node",
                "verbose_name_plural": "Call Tree Nodes",
                "ordering": ["call_tree", "order"],
            },
        ),
        migrations.CreateModel(
            name="BusinessImpactAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assessment_date", models.DateField(verbose_name="Assessment Date")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("approved", "Approved"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "rto_hours",
                    models.PositiveIntegerField(
                        help_text="هدف وقت الاستعادة - Recovery Time Objective",
                        verbose_name="RTO (Hours)",
                    ),
                ),
                (
                    "rpo_hours",
                    models.PositiveIntegerField(
                        help_text="هدف نقطة الاستعادة - Recovery Point Objective",
                        verbose_name="RPO (Hours)",
                    ),
                ),
                (
                    "mtpd_hours",
                    models.PositiveIntegerField(
                        help_text="أقصى فترة توقف مقبولة - Maximum Tolerable Period of Disruption",
                        verbose_name="MTPD (Hours)",
                    ),
                ),
                (
                    "impact_1_hour",
                    models.PositiveIntegerField(
                        default=1, help_text="1-5 scale", verbose_name="Impact (1 Hour)"
                    ),
                ),
                (
                    "impact_4_hours",
                    models.PositiveIntegerField(
                        default=2,
                        help_text="1-5 scale",
                        verbose_name="Impact (4 Hours)",
                    ),
                ),
                (
                    "impact_8_hours",
                    models.PositiveIntegerField(
                        default=3,
                        help_text="1-5 scale",
                        verbose_name="Impact (8 Hours)",
                    ),
                ),
                (
                    "impact_24_hours",
                    models.PositiveIntegerField(
                        default=4,
                        help_text="1-5 scale",
                        verbose_name="Impact (24 Hours)",
                    ),
                ),
                (
                    "impact_72_hours",
                    models.PositiveIntegerField(
                        default=5,
                        help_text="1-5 scale",
                        verbose_name="Impact (72 Hours)",
                    ),
                ),
                (
                    "financial_impact_daily",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="Financial Impact (Daily SAR)",
                    ),
                ),
                (
                    "operational_impact",
                    models.TextField(verbose_name="Operational Impact"),
                ),
                (
                    "operational_impact_ar",
                    models.TextField(blank=True, verbose_name="الأثر التشغيلي"),
                ),
                (
                    "reputational_impact",
                    models.TextField(blank=True, verbose_name="Reputational Impact"),
                ),
                (
                    "reputational_impact_ar",
                    models.TextField(blank=True, verbose_name="الأثر السمعي"),
                ),
                (
                    "regulatory_impact",
                    models.TextField(
                        blank=True, verbose_name="Regulatory/Legal Impact"
                    ),
                ),
                (
                    "regulatory_impact_ar",
                    models.TextField(
                        blank=True, verbose_name="الأثر التنظيمي/القانوني"
                    ),
                ),
                (
                    "staff_dependencies",
                    models.TextField(blank=True, verbose_name="Staff Dependencies"),
                ),
                (
                    "staff_dependencies_ar",
                    models.TextField(
                        blank=True, verbose_name="الاعتمادية على الموظفين"
                    ),
                ),
                (
                    "system_dependencies",
                    models.TextField(blank=True, verbose_name="System/IT Dependencies"),
                ),
                (
                    "system_dependencies_ar",
                    models.TextField(blank=True, verbose_name="الاعتمادية على الأنظمة"),
                ),
                (
                    "vendor_dependencies",
                    models.TextField(
                        blank=True, verbose_name="Vendor/Third-party Dependencies"
                    ),
                ),
                (
                    "vendor_dependencies_ar",
                    models.TextField(
                        blank=True, verbose_name="الاعتمادية على الموردين"
                    ),
                ),
                (
                    "minimum_staff",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Minimum Staff Required"
                    ),
                ),
                (
                    "minimum_equipment",
                    models.TextField(blank=True, verbose_name="Minimum Equipment"),
                ),
                (
                    "minimum_equipment_ar",
                    models.TextField(blank=True, verbose_name="الحد الأدنى من المعدات"),
                ),
                (
                    "peak_periods",
                    models.TextField(blank=True, verbose_name="Peak/Critical Periods"),
                ),
                (
                    "peak_periods_ar",
                    models.TextField(blank=True, verbose_name="فترات الذروة"),
                ),
                (
                    "approved_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Approved Date"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_bias",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Approved By",
                    ),
                ),
                (
                    "assessor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conducted_bias",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Assessor",
                    ),
                ),
                (
                    "business_function",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bias",
                        to="bcm.businessfunction",
                        verbose_name="Business Function",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bias",
                        to="core.organization",
                        verbose_name="Organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Business Impact Analysis",
                "verbose_name_plural": "Business Impact Analyses",
                "ordering": ["-assessment_date"],
            },
        ),
        migrations.AddField(
            model_name="bcplan",
            name="covered_functions",
            field=models.ManyToManyField(
                related_name="bc_plans",
                to="bcm.businessfunction",
                verbose_name="Covered Functions",
            ),
        ),
        migrations.AddField(
            model_name="bcplan",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_bc_plans",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AddField(
            model_name="bcplan",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bc_plans",
                to="core.organization",
                verbose_name="Organization",
            ),
        ),
        migrations.AddField(
            model_name="bcplan",
            name="owner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_bc_plans",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Plan Owner",
            ),
        ),
        migrations.CreateModel(
            name="BCMTestFinding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=300, verbose_name="Finding Title"),
                ),
                (
                    "title_ar",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="عنوان النتيجة"
                    ),
                ),
                ("description", models.TextField(verbose_name="Finding Description")),
                (
                    "description_ar",
                    models.TextField(blank=True, verbose_name="وصف النتيجة"),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=20,
                        verbose_name="Severity",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("in_progress", "In Progress"),
                            ("resolved", "Resolved"),
                            ("accepted", "Accepted"),
                        ],
                        default="open",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("recommendation", models.TextField(verbose_name="Recommendation")),
                (
                    "recommendation_ar",
                    models.TextField(blank=True, verbose_name="التوصية"),
                ),
                (
                    "due_date",
                    models.DateField(blank=True, null=True, verbose_name="Due Date"),
                ),
                ("resolution", models.TextField(blank=True, verbose_name="Resolution")),
                ("resolution_ar", models.TextField(blank=True, verbose_name="الحل")),
                (
                    "resolved_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Resolved Date"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_bcm_findings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Assigned To",
                    ),
                ),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="findings",
                        to="bcm.bcmtest",
                        verbose_name="Test",
                    ),
                ),
            ],
            options={
                "verbose_name": "BCM Test Finding",
                "verbose_name_plural": "BCM Test Findings",
                "ordering": ["-severity", "-created_at"],
            },
        ),
        migrations.AddField(
            model_name="bcmtest",
            name="bc_plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tests",
                to="bcm.bcplan",
                verbose_name="BCP Being Tested",
            ),
        ),
        migrations.AddField(
            model_name="bcmtest",
            name="coordinator",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="coordinated_tests",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Test Coordinator",
            ),
        ),
        migrations.AddField(
            model_name="bcmtest",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_bcm_tests",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AddField(
            model_name="bcmtest",
            name="dr_plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tests",
                to="bcm.disasterrecoveryplan",
                verbose_name="DRP Being Tested",
            ),
        ),
        migrations.AddField(
            model_name="bcmtest",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bcm_tests",
                to="core.organization",
                verbose_name="Organization",
            ),
        ),
        migrations.AddField(
            model_name="bcmtest",
            name="participants",
            field=models.ManyToManyField(
                blank=True,
                related_name="bcm_test_participations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Participants",
            ),
        ),
        migrations.CreateModel(
            name="CrisisTeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("commander", "Incident Commander"),
                            ("deputy", "Deputy Commander"),
                            ("operations", "Operations Lead"),
                            ("communications", "Communications Lead"),
                            ("logistics", "Logistics Lead"),
                            ("hr", "HR Lead"),
                            ("it", "IT Lead"),
                            ("finance", "Finance Lead"),
                            ("member", "Team Member"),
                        ],
                        default="member",
                        max_length=20,
                        verbose_name="Role",
                    ),
                ),
                (
                    "role_description",
                    models.TextField(blank=True, verbose_name="Role Description"),
                ),
                (
                    "role_description_ar",
                    models.TextField(blank=True, verbose_name="وصف الدور"),
                ),
                (
                    "primary_phone",
                    models.CharField(max_length=20, verbose_name="Primary Phone"),
                ),
                (
                    "secondary_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Secondary Phone"
                    ),
                ),
                (
                    "personal_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Personal Email"
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(default=True, verbose_name="Primary Contact"),
                ),
                (
                    "backup_member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="backup_for",
                        to="bcm.crisisteammember",
                        verbose_name="Backup Member",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="bcm.crisismanagementteam",
                        verbose_name="Team",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crisis_team_roles",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Crisis Team Member",
                "verbose_name_plural": "Crisis Team Members",
                "unique_together": {("team", "user")},
            },
        ),
        migrations.CreateModel(
            name="CrisisIncident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "incident_id",
                    models.CharField(max_length=50, verbose_name="Incident ID"),
                ),
                (
                    "title",
                    models.CharField(max_length=300, verbose_name="Incident Title"),
                ),
                (
                    "title_ar",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="عنوان الحادثة"
                    ),
                ),
                (
                    "incident_type",
                    models.CharField(
                        choices=[
                            ("natural_disaster", "Natural Disaster"),
                            ("cyber_attack", "Cyber Attack"),
                            ("infrastructure", "Infrastructure Failure"),
                            ("pandemic", "Pandemic"),
                            ("security", "Security Incident"),
                            ("operational", "Operational Disruption"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                        verbose_name="Incident Type",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=20,
                        verbose_name="Severity",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("reported", "Reported"),
                            ("assessing", "Assessing"),
                            ("responding", "Responding"),
                            ("recovering", "Recovering"),
                            ("resolved", "Resolved"),
                            ("closed", "Closed"),
                        ],
                        default="reported",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("description", models.TextField(verbose_name="Description")),
                ("description_ar", models.TextField(blank=True, verbose_name="الوصف")),
                (
                    "impact_description",
                    models.TextField(verbose_name="Impact Description"),
                ),
                (
                    "impact_description_ar",
                    models.TextField(blank=True, verbose_name="وصف الأثر"),
                ),
                (
                    "response_actions",
                    models.TextField(blank=True, verbose_name="Response Actions"),
                ),
                (
                    "response_actions_ar",
                    models.TextField(blank=True, verbose_name="إجراءات الاستجابة"),
                ),
                ("reported_at", models.DateTimeField(verbose_name="Reported At")),
                (
                    "declared_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Crisis Declared At"
                    ),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Resolved At"
                    ),
                ),
                (
                    "closed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Closed At"
                    ),
                ),
                (
                    "lessons_learned",
                    models.TextField(blank=True, verbose_name="Lessons Learned"),
                ),
                (
                    "lessons_learned_ar",
                    models.TextField(blank=True, verbose_name="الدروس المستفادة"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "activated_bc_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="incidents",
                        to="bcm.bcplan",
                        verbose_name="Activated BCP",
                    ),
                ),
                (
                    "activated_dr_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="incidents",
                        to="bcm.disasterrecoveryplan",
                        verbose_name="Activated DRP",
                    ),
                ),
                (
                    "affected_functions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="crisis_incidents",
                        to="bcm.businessfunction",
                        verbose_name="Affected Functions",
                    ),
                ),
                (
                    "crisis_team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="incidents",
                        to="bcm.crisismanagementteam",
                        verbose_name="Assigned Crisis Team",
                    ),
                ),
                (
                    "incident_commander",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="commanded_incidents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Incident Commander",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crisis_incidents",
                        to="core.organization",
                        verbose_name="Organization",
                    ),
                ),
                (
                    "reported_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reported_incidents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Reported By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Crisis Incident",
                "verbose_name_plural": "Crisis Incidents",
                "ordering": ["-reported_at"],
                "unique_together": {("organization", "incident_id")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="bcplan", unique_together={("organization", "plan_id")},
        ),
        migrations.AlterUniqueTogether(
            name="bcmtest", unique_together={("organization", "test_id")},
        ),
    ]
