# Generated by Django 4.2.27 on 2026-01-18 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bcm", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bcmtest",
            name="objectives",
            field=models.TextField(blank=True, verbose_name="Test Objectives"),
        ),
        migrations.AlterField(
            model_name="bcmtest",
            name="scope",
            field=models.TextField(blank=True, verbose_name="Test Scope"),
        ),
        migrations.AlterField(
            model_name="bcplan",
            name="activation_criteria",
            field=models.TextField(blank=True, verbose_name="Activation Criteria"),
        ),
        migrations.AlterField(
            model_name="bcplan",
            name="communication_plan",
            field=models.TextField(blank=True, verbose_name="Communication Plan"),
        ),
        migrations.AlterField(
            model_name="bcplan",
            name="objectives",
            field=models.TextField(blank=True, verbose_name="Objectives"),
        ),
        migrations.AlterField(
            model_name="bcplan",
            name="recovery_strategies",
            field=models.TextField(blank=True, verbose_name="Recovery Strategies"),
        ),
        migrations.AlterField(
            model_name="bcplan",
            name="roles_responsibilities",
            field=models.TextField(
                blank=True, verbose_name="Roles and Responsibilities"
            ),
        ),
        migrations.AlterField(
            model_name="bcplan",
            name="scope",
            field=models.TextField(blank=True, verbose_name="Plan Scope"),
        ),
        migrations.AlterField(
            model_name="disasterrecoveryplan",
            name="backup_strategy",
            field=models.TextField(blank=True, verbose_name="Backup Strategy"),
        ),
        migrations.AlterField(
            model_name="disasterrecoveryplan",
            name="covered_systems",
            field=models.TextField(blank=True, verbose_name="Covered Systems"),
        ),
        migrations.AlterField(
            model_name="disasterrecoveryplan",
            name="recovery_procedures",
            field=models.TextField(blank=True, verbose_name="Recovery Procedures"),
        ),
        migrations.AlterField(
            model_name="disasterrecoveryplan",
            name="scope",
            field=models.TextField(blank=True, verbose_name="Plan Scope"),
        ),
    ]
