# Generated by Django 4.2.27 on 2026-01-18 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bcm", "0002_alter_bcmtest_objectives_alter_bcmtest_scope_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="businessimpactanalysis",
            name="assessment_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Assessment Date"
            ),
        ),
        migrations.AlterField(
            model_name="businessimpactanalysis",
            name="business_function",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bias",
                to="bcm.businessfunction",
                verbose_name="Business Function",
            ),
        ),
        migrations.AlterField(
            model_name="businessimpactanalysis",
            name="mtpd_hours",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="أقصى فترة توقف مقبولة - Maximum Tolerable Period of Disruption",
                null=True,
                verbose_name="MTPD (Hours)",
            ),
        ),
        migrations.AlterField(
            model_name="businessimpactanalysis",
            name="operational_impact",
            field=models.TextField(blank=True, verbose_name="Operational Impact"),
        ),
        migrations.AlterField(
            model_name="businessimpactanalysis",
            name="rpo_hours",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="هدف نقطة الاستعادة - Recovery Point Objective",
                null=True,
                verbose_name="RPO (Hours)",
            ),
        ),
        migrations.AlterField(
            model_name="businessimpactanalysis",
            name="rto_hours",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="هدف وقت الاستعادة - Recovery Time Objective",
                null=True,
                verbose_name="RTO (Hours)",
            ),
        ),
    ]
