# Generated by Django 4.2.27 on 2026-01-15 21:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("compliance", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("asset_id", models.CharField(max_length=50, verbose_name="Asset ID")),
                ("name", models.CharField(max_length=300, verbose_name="Asset Name")),
                (
                    "name_ar",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="اسم الأصل"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                ("description_ar", models.TextField(blank=True, verbose_name="الوصف")),
                (
                    "criticality",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=20,
                        verbose_name="Criticality",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("retired", "Retired"),
                            ("under_review", "Under Review"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "confidentiality_value",
                    models.PositiveIntegerField(
                        default=3, verbose_name="Confidentiality Value (1-5)"
                    ),
                ),
                (
                    "integrity_value",
                    models.PositiveIntegerField(
                        default=3, verbose_name="Integrity Value (1-5)"
                    ),
                ),
                (
                    "availability_value",
                    models.PositiveIntegerField(
                        default=3, verbose_name="Availability Value (1-5)"
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Location"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Asset",
                "verbose_name_plural": "Assets",
                "ordering": ["-criticality", "name"],
            },
        ),
        migrations.CreateModel(
            name="AssetCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Category Name"),
                ),
                (
                    "name_ar",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="اسم التصنيف"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Category Code"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                ("description_ar", models.TextField(blank=True, verbose_name="الوصف")),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
            ],
            options={
                "verbose_name": "Asset Category",
                "verbose_name_plural": "Asset Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Risk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("risk_id", models.CharField(max_length=50, verbose_name="Risk ID")),
                ("title", models.CharField(max_length=300, verbose_name="Risk Title")),
                (
                    "title_ar",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="عنوان المخاطر"
                    ),
                ),
                ("description", models.TextField(verbose_name="Risk Description")),
                (
                    "description_ar",
                    models.TextField(blank=True, verbose_name="وصف المخاطر"),
                ),
                (
                    "risk_type",
                    models.CharField(
                        choices=[
                            ("strategic", "Strategic"),
                            ("operational", "Operational"),
                            ("financial", "Financial"),
                            ("compliance", "Compliance"),
                            ("cyber", "Cybersecurity"),
                            ("reputational", "Reputational"),
                            ("other", "Other"),
                        ],
                        default="operational",
                        max_length=20,
                        verbose_name="Risk Type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("identified", "Identified"),
                            ("assessed", "Assessed"),
                            ("treating", "Under Treatment"),
                            ("monitoring", "Monitoring"),
                            ("closed", "Closed"),
                        ],
                        default="identified",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "risk_source",
                    models.TextField(blank=True, verbose_name="Risk Source"),
                ),
                (
                    "risk_source_ar",
                    models.TextField(blank=True, verbose_name="مصدر المخاطر"),
                ),
                (
                    "inherent_likelihood",
                    models.PositiveIntegerField(
                        default=3, verbose_name="Inherent Likelihood (1-5)"
                    ),
                ),
                (
                    "inherent_impact",
                    models.PositiveIntegerField(
                        default=3, verbose_name="Inherent Impact (1-5)"
                    ),
                ),
                (
                    "residual_likelihood",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Residual Likelihood (1-5)"
                    ),
                ),
                (
                    "residual_impact",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Residual Impact (1-5)"
                    ),
                ),
                (
                    "target_likelihood",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Target Likelihood (1-5)"
                    ),
                ),
                (
                    "target_impact",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Target Impact (1-5)"
                    ),
                ),
                (
                    "identified_date",
                    models.DateField(auto_now_add=True, verbose_name="Identified Date"),
                ),
                (
                    "review_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Next Review Date"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "assets",
                    models.ManyToManyField(
                        blank=True,
                        related_name="risks",
                        to="risk.asset",
                        verbose_name="Related Assets",
                    ),
                ),
            ],
            options={
                "verbose_name": "Risk",
                "verbose_name_plural": "Risks",
                "ordering": ["-inherent_likelihood", "-inherent_impact"],
            },
        ),
        migrations.CreateModel(
            name="RiskTreatment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "treatment_option",
                    models.CharField(
                        choices=[
                            ("mitigate", "Mitigate"),
                            ("transfer", "Transfer"),
                            ("accept", "Accept"),
                            ("avoid", "Avoid"),
                        ],
                        max_length=20,
                        verbose_name="Treatment Option",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=300, verbose_name="Treatment Title"),
                ),
                (
                    "title_ar",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="عنوان المعالجة"
                    ),
                ),
                ("description", models.TextField(verbose_name="Treatment Description")),
                (
                    "description_ar",
                    models.TextField(blank=True, verbose_name="وصف المعالجة"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("deferred", "Deferred"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="planned",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "expected_residual_likelihood",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Expected Residual Likelihood",
                    ),
                ),
                (
                    "expected_residual_impact",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Expected Residual Impact"
                    ),
                ),
                (
                    "estimated_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Estimated Cost",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(blank=True, null=True, verbose_name="Start Date"),
                ),
                (
                    "due_date",
                    models.DateField(blank=True, null=True, verbose_name="Due Date"),
                ),
                (
                    "completed_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Completed Date"
                    ),
                ),
                (
                    "progress_percentage",
                    models.PositiveIntegerField(default=0, verbose_name="Progress (%)"),
                ),
                (
                    "progress_notes",
                    models.TextField(blank=True, verbose_name="Progress Notes"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_treatments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_treatments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Treatment Owner",
                    ),
                ),
                (
                    "risk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="treatments",
                        to="risk.risk",
                        verbose_name="Risk",
                    ),
                ),
            ],
            options={
                "verbose_name": "Risk Treatment",
                "verbose_name_plural": "Risk Treatments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RiskCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Category Name"),
                ),
                (
                    "name_ar",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="اسم التصنيف"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Category Code"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                ("description_ar", models.TextField(blank=True, verbose_name="الوصف")),
                (
                    "color",
                    models.CharField(
                        default="#6c757d", max_length=7, verbose_name="Color"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="risk.riskcategory",
                        verbose_name="Parent Category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Risk Category",
                "verbose_name_plural": "Risk Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="RiskAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assessment_type",
                    models.CharField(
                        choices=[
                            ("initial", "Initial Assessment"),
                            ("periodic", "Periodic Review"),
                            ("incident", "Post-Incident"),
                            ("change", "Change-Triggered"),
                        ],
                        default="periodic",
                        max_length=20,
                        verbose_name="Assessment Type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("approved", "Approved"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("assessment_date", models.DateField(verbose_name="Assessment Date")),
                (
                    "likelihood_score",
                    models.PositiveIntegerField(verbose_name="Likelihood Score (1-5)"),
                ),
                (
                    "likelihood_rationale",
                    models.TextField(verbose_name="Likelihood Rationale"),
                ),
                (
                    "likelihood_rationale_ar",
                    models.TextField(blank=True, verbose_name="مبررات الاحتمالية"),
                ),
                (
                    "impact_score",
                    models.PositiveIntegerField(verbose_name="Impact Score (1-5)"),
                ),
                ("impact_rationale", models.TextField(verbose_name="Impact Rationale")),
                (
                    "impact_rationale_ar",
                    models.TextField(blank=True, verbose_name="مبررات الأثر"),
                ),
                (
                    "control_effectiveness",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Percentage of risk reduced by controls",
                        verbose_name="Control Effectiveness (%)",
                    ),
                ),
                (
                    "findings",
                    models.TextField(blank=True, verbose_name="Assessment Findings"),
                ),
                (
                    "findings_ar",
                    models.TextField(blank=True, verbose_name="نتائج التقييم"),
                ),
                (
                    "recommendations",
                    models.TextField(blank=True, verbose_name="Recommendations"),
                ),
                (
                    "recommendations_ar",
                    models.TextField(blank=True, verbose_name="التوصيات"),
                ),
                (
                    "approved_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Approved Date"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_risk_assessments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Approved By",
                    ),
                ),
                (
                    "assessor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="risk_assessments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Assessor",
                    ),
                ),
                (
                    "risk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessments",
                        to="risk.risk",
                        verbose_name="Risk",
                    ),
                ),
            ],
            options={
                "verbose_name": "Risk Assessment",
                "verbose_name_plural": "Risk Assessments",
                "ordering": ["-assessment_date"],
            },
        ),
        migrations.CreateModel(
            name="RiskAcceptance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("justification", models.TextField(verbose_name="Justification")),
                (
                    "justification_ar",
                    models.TextField(blank=True, verbose_name="المبررات"),
                ),
                (
                    "conditions",
                    models.TextField(blank=True, verbose_name="Acceptance Conditions"),
                ),
                (
                    "conditions_ar",
                    models.TextField(blank=True, verbose_name="شروط القبول"),
                ),
                (
                    "accepted_likelihood",
                    models.PositiveIntegerField(verbose_name="Accepted Likelihood"),
                ),
                (
                    "accepted_impact",
                    models.PositiveIntegerField(verbose_name="Accepted Impact"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("valid_from", models.DateField(verbose_name="Valid From")),
                ("valid_until", models.DateField(verbose_name="Valid Until")),
                (
                    "requested_date",
                    models.DateField(auto_now_add=True, verbose_name="Requested Date"),
                ),
                (
                    "approved_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Approved Date"
                    ),
                ),
                (
                    "approval_comments",
                    models.TextField(blank=True, verbose_name="Approval Comments"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_acceptances",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Approved By",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requested_acceptances",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Requested By",
                    ),
                ),
                (
                    "risk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="acceptances",
                        to="risk.risk",
                        verbose_name="Risk",
                    ),
                ),
            ],
            options={
                "verbose_name": "Risk Acceptance",
                "verbose_name_plural": "Risk Acceptances",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="risk",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="risks",
                to="risk.riskcategory",
                verbose_name="Category",
            ),
        ),
        migrations.AddField(
            model_name="risk",
            name="controls",
            field=models.ManyToManyField(
                blank=True,
                related_name="mitigated_risks",
                to="compliance.control",
                verbose_name="Mitigating Controls",
            ),
        ),
        migrations.AddField(
            model_name="risk",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_risks",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AddField(
            model_name="risk",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="risks",
                to="core.department",
                verbose_name="Department",
            ),
        ),
        migrations.AddField(
            model_name="risk",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="risks",
                to="core.organization",
                verbose_name="Organization",
            ),
        ),
        migrations.AddField(
            model_name="risk",
            name="owner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_risks",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Risk Owner",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assets",
                to="risk.assetcategory",
                verbose_name="Category",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_assets",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="custodian",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="custodian_assets",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Asset Custodian",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assets",
                to="core.department",
                verbose_name="Department",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assets",
                to="core.organization",
                verbose_name="Organization",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="owner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_assets",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Asset Owner",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="risk", unique_together={("organization", "risk_id")},
        ),
        migrations.AlterUniqueTogether(
            name="asset", unique_together={("organization", "asset_id")},
        ),
    ]
