# Generated by Django 4.2.27 on 2026-01-16 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("risk", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="risk",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="risks",
                to="risk.riskcategory",
                verbose_name="Category",
            ),
        ),
        migrations.AlterField(
            model_name="risk",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_risks",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Risk Owner",
            ),
        ),
    ]
