# Generated by Django 4.2.27 on 2026-01-18 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("risk", "0002_alter_risk_category_alter_risk_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="risk",
            name="description",
            field=models.TextField(blank=True, verbose_name="Risk Description"),
        ),
    ]
