# Generated by Django 4.2.27 on 2026-01-15 21:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkflowTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Workflow Name"),
                ),
                (
                    "name_ar",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="اسم سير العمل"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Workflow Code"
                    ),
                ),
                (
                    "workflow_type",
                    models.CharField(
                        choices=[
                            ("approval", "Approval Workflow"),
                            ("review", "Review Workflow"),
                            ("sequential", "Sequential Workflow"),
                            ("parallel", "Parallel Workflow"),
                        ],
                        default="approval",
                        max_length=20,
                        verbose_name="Workflow Type",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                ("description_ar", models.TextField(blank=True, verbose_name="الوصف")),
                (
                    "applicable_models",
                    models.JSONField(
                        default=list,
                        help_text="List of model types this workflow applies to",
                        verbose_name="Applicable Models",
                    ),
                ),
                (
                    "default_sla_days",
                    models.PositiveIntegerField(
                        default=5, verbose_name="Default SLA (Days)"
                    ),
                ),
                (
                    "escalation_enabled",
                    models.BooleanField(
                        default=True, verbose_name="Escalation Enabled"
                    ),
                ),
                (
                    "escalation_days",
                    models.PositiveIntegerField(
                        default=3, verbose_name="Escalation After (Days)"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_workflow_templates",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Workflow Template",
                "verbose_name_plural": "Workflow Templates",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="WorkflowStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(verbose_name="Step Order")),
                ("name", models.CharField(max_length=200, verbose_name="Step Name")),
                (
                    "name_ar",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="اسم الخطوة"
                    ),
                ),
                (
                    "step_type",
                    models.CharField(
                        choices=[
                            ("approval", "Approval"),
                            ("review", "Review"),
                            ("notification", "Notification"),
                            ("task", "Task"),
                        ],
                        default="approval",
                        max_length=20,
                        verbose_name="Step Type",
                    ),
                ),
                (
                    "assignee_type",
                    models.CharField(
                        choices=[
                            ("user", "Specific User"),
                            ("role", "Role"),
                            ("manager", "Department Manager"),
                            ("owner", "Object Owner"),
                        ],
                        default="role",
                        max_length=20,
                        verbose_name="Assignee Type",
                    ),
                ),
                (
                    "sla_days",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="SLA (Days)"
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(default=True, verbose_name="Required"),
                ),
                (
                    "allow_delegation",
                    models.BooleanField(default=True, verbose_name="Allow Delegation"),
                ),
                (
                    "instructions",
                    models.TextField(blank=True, verbose_name="Instructions"),
                ),
                (
                    "instructions_ar",
                    models.TextField(blank=True, verbose_name="التعليمات"),
                ),
                (
                    "assignee_role",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="workflow_steps",
                        to="core.role",
                        verbose_name="Assignee Role",
                    ),
                ),
                (
                    "assignee_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_workflow_steps",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Assignee User",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="workflow.workflowtemplate",
                        verbose_name="Workflow Template",
                    ),
                ),
            ],
            options={
                "verbose_name": "Workflow Step",
                "verbose_name_plural": "Workflow Steps",
                "ordering": ["template", "order"],
                "unique_together": {("template", "order")},
            },
        ),
        migrations.CreateModel(
            name="WorkflowInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_type",
                    models.CharField(max_length=100, verbose_name="Content Type"),
                ),
                ("object_id", models.PositiveIntegerField(verbose_name="Object ID")),
                (
                    "object_title",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Object Title"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "current_step",
                    models.PositiveIntegerField(default=1, verbose_name="Current Step"),
                ),
                (
                    "started_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Started At"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Completed At"
                    ),
                ),
                (
                    "due_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Due Date"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "initiated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="initiated_workflows",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Initiated By",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="instances",
                        to="workflow.workflowtemplate",
                        verbose_name="Workflow Template",
                    ),
                ),
            ],
            options={
                "verbose_name": "Workflow Instance",
                "verbose_name_plural": "Workflow Instances",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="Task Title")),
                (
                    "title_ar",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="عنوان المهمة"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                ("description_ar", models.TextField(blank=True, verbose_name="الوصف")),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("general", "General Task"),
                            ("review", "Review Task"),
                            ("assessment", "Assessment Task"),
                            ("evidence", "Evidence Collection"),
                            ("audit", "Audit Task"),
                            ("remediation", "Remediation Task"),
                        ],
                        default="general",
                        max_length=20,
                        verbose_name="Task Type",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=20,
                        verbose_name="Priority",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("overdue", "Overdue"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Content Type"
                    ),
                ),
                (
                    "object_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Object ID"
                    ),
                ),
                (
                    "due_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Due Date"
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Started At"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Completed At"
                    ),
                ),
                (
                    "completion_notes",
                    models.TextField(blank=True, verbose_name="Completion Notes"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "assigned_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Assigned By",
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Assigned To",
                    ),
                ),
                (
                    "workflow_instance",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tasks",
                        to="workflow.workflowinstance",
                        verbose_name="Workflow Instance",
                    ),
                ),
            ],
            options={
                "verbose_name": "Task",
                "verbose_name_plural": "Tasks",
                "ordering": ["-priority", "due_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Approval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("delegated", "Delegated"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "decided_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Decided At"
                    ),
                ),
                ("comments", models.TextField(blank=True, verbose_name="Comments")),
                (
                    "delegated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Delegated At"
                    ),
                ),
                (
                    "due_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Due Date"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "assignee",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_approvals",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Assignee",
                    ),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="decided_approvals",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Decided By",
                    ),
                ),
                (
                    "delegated_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="delegated_approvals",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Delegated To",
                    ),
                ),
                (
                    "step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approvals",
                        to="workflow.workflowstep",
                        verbose_name="Workflow Step",
                    ),
                ),
                (
                    "workflow_instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approvals",
                        to="workflow.workflowinstance",
                        verbose_name="Workflow Instance",
                    ),
                ),
            ],
            options={
                "verbose_name": "Approval",
                "verbose_name_plural": "Approvals",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="workflowinstance",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="workflow_wo_content_940087_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="workflowinstance",
            index=models.Index(
                fields=["status", "due_date"], name="workflow_wo_status_0e4bfb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["assigned_to", "status"], name="workflow_ta_assigne_e0a0c5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["due_date", "status"], name="workflow_ta_due_dat_3f93b3_idx"
            ),
        ),
    ]
