# Generated by Django 4.2.27 on 2026-01-21 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('workflow_started', 'Workflow Started'), ('workflow_completed', 'Workflow Completed'), ('workflow_rejected', 'Workflow Rejected'), ('workflow_cancelled', 'Workflow Cancelled'), ('approval_decision', 'Approval Decision'), ('approval_delegated', 'Approval Delegated'), ('task_assigned', 'Task Assigned'), ('task_completed', 'Task Completed'), ('escalation', 'Escalation'), ('reminder_sent', 'Reminder Sent'), ('comment_added', 'Comment Added')], max_length=30, verbose_name='Action')),
                ('details', models.TextField(blank=True, verbose_name='Details')),
                ('step_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Step Number')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_actions', to=settings.AUTH_USER_MODEL, verbose_name='Performed By')),
                ('workflow_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='workflow.workflowinstance', verbose_name='Workflow Instance')),
            ],
            options={
                'verbose_name': 'Workflow History',
                'verbose_name_plural': 'Workflow History',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['workflow_instance', '-created_at'], name='workflow_wo_workflo_6939ee_idx')],
            },
        ),
    ]
