# Generated by Django 4.2.27 on 2026-01-21 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0002_create_content_approval_workflow'),
        ('workflow', '0002_workflowhistory'),
    ]

    operations = [
    ]
